### ISSUE TITLE
Default sigma change in mnnCorrect

### ISSUE THREAD

**Issue by yueqiw** [MarioniLab/scran#11]
Hi,

The default value of sigma has changed from 1.0 to 0.1, but the documentation still says: 
> The choice of sigma determines the extent of smoothing - a value of 1 is used by default to reflect the boundaries of the space after cosine normalization

What's the reason behind the change? Is 0.1 a better parameter for most use cases? Thanks!

**Comment by LTLA** [comment]
Yes, because it seems to better preserve locality of the batch effect. I have updated the documentation.

You may be interested in the `bettermnn` branch of _scran_, which provides the `fastMNN` function. This is, as the name suggests, much faster than `mnnCorrect`, and it avoids the need for `sigma` altogether.

**Comment by yueqiw** [comment]
Thanks! To me, sigma = 1 works pretty well with the known common cell types being batch-corrected. I tried sigma = 0.1 on my data with 4 batches and the it failed to correct the batch effect. So I was curious about the change of default value. How are the locality of batch effects evaluated? And will there be any vignette comparing the effect of sigma values on published result in the mnnCorrect paper? Thanks!

**Comment by LTLA** [comment]
Let me get a rant out of the way first. To be clear, local batch effects only occur in the "worst-case" scenario where batch effects are different between cell types. I say this is the worst case because it fundamentally compromises our ability to quantitatively describe the differences between cell types. For example, a log-fold change of 2 for your marker gene in your first batch might become a log-fold fold change of 1 (or 5, or 10) in your second batch. Sure, we can still distinguish between the cell types, but if we can't measure the differences reproducibly, it's difficult to trust the data in any quantitative sense.

Okay, onto your observations. They're unusual because a lower `sigma` should err towards over-correction. Indeed, with a `sigma` approaching zero, each cell in one batch will just be mapped directly to (the average of) the mutually nearest neighbours in the other batch. So with a very low `sigma`, the mixing between batches should get "better" and the batch effect should "disappear". (To digress somewhat, I've used quotation marks to reflect the typical remarks I get from data analysts who apply the method to their data, and then complain to me about the results. The only way to really evaluate a method is either with simulations or with a high-quality ground truth dataset, and the latter is extremely rare at the single-cell level. For example, is that cell type _really_ homogeneous? Are those two populations _really_ different?) In contrast, a larger `sigma` will generally under-correct, while providing greater stability to the correction vectors. This is why seeing a "better" correction with a larger `sigma` is unusual. 

We don't have a direct comparison of results with differing `sigma`, but `sigma=0.1` was used to generate most of the results in the paper (see https://github.com/MarioniLab/MNN2017). And in-house use has shown that "better" merging of batches occurs with a lower `sigma`. So it made sense to change the default - which, to be honest, was chosen more on theoretical rather than practical grounds anyway.

The easiest and most interpretable way to evaluate the locality of batch effects is to test for interaction effects between batch and cell type, e.g., using _edgeR_. If these interaction effects are non-zero, it implies that the batch effect for one cell type is different from the batch effect for another cell type.

**Comment by yueqiw** [comment]
Thanks for the detailed answer! 

> sigma=0.1 was used to generate most of the results in the paper

I was under the impression that the paper used the previous default sigma of 1.0, since the main text of the paper did not discuss kernel bandwidth, and the Supplementary Note 5 says the following: 
> We choose the default Gaussian kernel width σ2 = 1 in the cosine normalized space

But of course, the code repository makes it clear that 0.1 was used in most cases. Thanks for posting the code!

I only tried sigma values of 0.1, 0.3 and 1.0. I got very similar results (almost identical clustering and batch distribution) from 0.3 and 1.0, so I think I'll use either one of them. What I saw from sigma=0.1 was some cells from each batch establishing their own "clusters" away from other cells on the t-SNE plot,  and more batch separation than uncorrected data. I guess it may have something to do with the stability to the correction vectors that you mentioned. Anyway, I think I got good enough results. Thanks for the detailed explanation!
