### ISSUE TITLE
makeTechTrend() throws error : 'to' must be a finite number

### ISSUE THREAD

**Issue by marcRDM** [MarioniLab/scran#14]
Hi,

I am trying to apply your beautiful 10X template (https://bioconductor.org/packages/release/workflows/vignettes/simpleSingleCell/inst/doc/work-3-tenx.html) to our data set. Everything seems about right until the computeSumFactors() step which warns me that it "encountered negative size factor estimates" which I can avoid with "positive = TRUE". In both cases, the next step, makeTechTrend() throws an error which I did not manage to track back in the source code : "Error in seq.default(from = 0, to = upper.value, length.out = 100) : 'to' must be a finite number".

Any idea what might be happening here?

Thank a million !

Cheers,
Marc

**Comment by LTLA** [comment]
The immediate error is caused by the fact that you have zero size factors - `positive=TRUE` is a misnomer as it only ensures that the size factors are non-negative. As a result, you end up with undefined log-transformed values in your log-expression matrix, `NA` subsequently complains because the internal calculations are not robust against `NA`s (and nor should they be; the `NA`s are the canary in the coal mine).

The real problem is with the fact that you need `positive=TRUE` at all. If you read `?computeSumFactors`, you will see that I don't think particularly highly of `positive=TRUE`. The underlying issue is that you're observing cells for which the median count - even after pooling! - is zero. I would argue that there is **no** way to normalize these cells effectively. The preferred solution is to perform more stringent quality control, as these are typically damaged cells that sneaked through somewhere - see my comments in [Section 4](https://bioconductor.org/packages/release/workflows/vignettes/simpleSingleCell/inst/doc/work-3-tenx.html#quality-control-on-the-cells).

If you must keep these cells, you can replace their size factors with the scaled library size, see https://github.com/MarioniLab/EmptyDrops2017/blob/master/analysis/pbmc4k/analysis.Rmd as an example. This is not an accurate normalization and just papers over the problem, but it will allow you to proceed to downstream analyses. Keep in mind that log-fold changes involving these cells will not be accurately computed as library size normalization does not resolve composition biases.

**Comment by marcRDM** [comment]
More stringent QC did the job ! Thanks Aaron !
