### ISSUE TITLE
Unexpected error when using fastMNN

### ISSUE THREAD

**Issue by VVictorChen** [MarioniLab/scran#18]
Thanks for your advice in the last question. We used the pipeline in
 [pipeline](https://www.bioconductor.org/packages/devel/workflows/vignettes/simpleSingleCell/inst/doc/work-5-mnn.html) 
All are perfect in the first time, but when we use other gene as variable genes, error appears.
```R
mnn.out <- do.call(fastMNN, c(original, list(k=50, d=50, approximate=TRUE, auto.order=TRUE)))
Error in (function (A, nv = 5, nu = nv, maxit = 100, work = nv + 7, reorth = TRUE,  :
  BLAS/LAPACK routine 'DLASCL' gave error code -4
```
Thanks & Best wishes

**Comment by LTLA** [comment]
You're going to have to be more specific. Provide some code to reproduce the error. Also, this question doesn't go here, but on the _simpleSingleCell_ repository (https://github.com/MarioniLab/simpleSingleCell).

**Comment by VVictorChen** [comment]
Here are the code. I will put the issue on the right place next time.  :)
```R
sc4 <- SingleCellExperiment(list(counts=as.matrix(ucb2)),
                           colData=DataFrame(Donor=name4))
#Quality control and normalization
set.seed(1000)
clusters <- quickCluster(sc4, method="igraph", min.mean=0.1)
table(clusters)
sc4 <- computeSumFactors(sc4, min.mean=0.1, clusters=clusters)
summary(sizeFactors(sc4))
sc4 <- normalize(sc4)
vg_seurat <- read.table(file = "*****.txt")
cor_vg <- Reduce(intersect, list(rownames(sc1), rownames(sc2), rownames(sc3), rownames(sc4),vg_seurat$x))
rescaled <- multiBatchNorm(sc1[cor_vg,], sc2[cor_vg,], sc3[cor_vg,], sc4[cor_vg,])
rescaled.sc1 <- rescaled[[1]]
rescaled.sc2 <- rescaled[[2]]
rescaled.sc3 <- rescaled[[3]]
rescaled.sc4 <- rescaled[[4]]
set.seed(100)
original <- list(
    GSEsc1=logcounts(rescaled.sc1)[cor_vg,],
    GSEsc2=logcounts(rescaled.sc2)[cor_vg,],
    GSEsc3=logcounts(rescaled.sc3)[cor_vg,],
    GSEsc4=logcounts(rescaled.sc4)[cor_vg,]
)
mnn.out <- do.call(fastMNN, c(original, list(k=50, d=50, approximate=TRUE, auto.order=TRUE)))
```
Thanks!

**Comment by LTLA** [comment]
I'm afraid that your latest post doesn't help; I can hardly reproduce the error when one of the file names is `"*****.txt"`. See https://stackoverflow.com/help/mcve for the expected level of debugging information. The actual error message would also help.

**Comment by VVictorChen** [comment]
I am sorry for this stupid  mistake. The real code is
```R
#input variable genes which are found according to Seurat package
vg_seurat <- read.table(file = "vargene.txt")
```

**Comment by LTLA** [comment]
Your are missing the point here. I need a bit of code that _I_ can run on _my_ computer in order to get the same error that you did. Again, see the link to the StackOverflow page that I posted above. You should also describe the error message in more detail than you have currently provided (i.e., none).

**Comment by gxg2002cn** [comment]
Hi, I met exactly the same error today when running fastMNN. Do you find a solution? Thanks!

**Comment by LTLA** [comment]
I don't have a solution because I can't reproduce the problem on my computer. I can't even try to reproduce it, because I don't have the data. If I had to guess, there are `NA`s somewhere in your input data. If you want to help to fix this problem, please provide an RDS file of the input data (anonymized as necessary) and the arguments with which you used to call `fastMNN`.

**Comment by gxg2002cn** [comment]
Dear Aaron,
Thanks a lot for your reply. I wonder how to run fastMNN without ERCC
spick-in even I added? I think my computer setup show be fine because I can
go though fastMNN by using example data. But for my data, it stop at
multiBatchNorm step. I thought because we used MARS-Seq with ERCC spick-in,
but ERCC at quite low level, therefore I limited the gene number to exclude
ERCC genes. It worked at this step, but new error came from next step,
fastMNN. "BLAS/LAPACK routine DLASCL gave error code -4" as figure
attached. I am a biologist and just very beginner of computer programming,
I simply put my data in dropbox (
https://www.dropbox.com/sh/chtd75kb4wg5ent/AADtTBmzawGPwVbvc4Wmwe3la?dl=0).
Hope you can figure out the problem and please let me know if you need any
further information.  Thank you very much for your great help.
Best regards,
Xiaogang


[image: image.png]
[image: image.png]

**Comment by LTLA** [comment]
Thanks @gxg2002cn. As I suspected, you have `NaN`s in your matrix, corresponding to the spike-ins genes (presumably because you have no counts for the spike-ins). After removing these rows, the function works:

```r
library(scran)
load("fastMNN_error.RData")

set.seed(1000)
not.erccs <- !grepl("ERCC", rownames(original[[1]]))
mnn.out <- do.call(fastMNN, c(original, list(k=20, d=50, approximate=TRUE, 
   subset.row=not.erccs)))
```

The output looks good, there seems to be decent mixing between batches on a t-SNE plot.

**Comment by gxg2002cn** [comment]
Great job! It´s working now. Thank you very much Aaron!
