### ISSUE TITLE
Ask about trendVar step

### ISSUE THREAD

**Issue by gxg2002cn** [MarioniLab/scran#21]
Hi again, I met an error when running trendVar in identifying highly variable genes as below.
"Error in model.frame.default(formula = to.fit ~ kept.means, weights = c(`1_EpiAPST2` = 59L,  : 
  variable lengths differ (found for 'kept.means')"
If set use.spikes=FALSE then no error. 
My questions are:
1. How to fix the error?

2. If it is a big differece use or don´t use spick-in here?
Thank you very much!

**Comment by LTLA** [comment]
If this is the same data set as #18, then you can't use spike-ins because they're all `NaN`. You have no choice but to fit the curve to endogenous genes - see the comments at http://bioconductor.org/packages/devel/workflows/vignettes/simpleSingleCell/inst/doc/xtra-3-var.html#32_when_spike-ins_are_unavailable.

**Comment by gxg2002cn** [comment]
Yes, it´s the same data as #18. I will remove the ERCC. Thanks a lot for
your help!
Best regards,
Xiaogang
