### ISSUE TITLE
fastMNN correction vector calculation

### ISSUE THREAD

**Issue by whitleyo** [MarioniLab/scran#43]
Hi,

Haven't quite delved into the source code yet, but in the documentation for the fastMNN function, it says for argument ndist:

A numeric scalar specifying the threshold beyond which neighbours are to be ignored when computing correction vectors. Each threshold is defined in terms of the number of median distances.
--

I'm wondering how cells with all neighbors exceeding this threshold have their correction vectors calculated, since those neighbors are to be ignored, if I understand correctly.

In the original paper (doi: 10.1038/nbt.4091) for MNN correction, it was stated that correction vectors for all cells would be a weighted average of the MNN vectors. 

Thanks for any help you're able to give.

**Comment by LTLA** [comment]
A cell can't have all neighbors exceeding the threshold, because the threshold for each cell is defined in terms of the number of median distances from its neighbors. So - at least for any `ndist > 1` - a cell must have at least one neighbor. (Specifically, at least one neighbor involved in a MNN pair; we don't consider uninvolved neighbors during the search at this step.)

**Comment by LTLA** [comment]
Also, I should point out that `fastMNN` now lives in https://github.com/LTLA/batchelor.

**Comment by LTLA** [comment]
This seems resolved, so closing. Feel free to reopen if something is unclear.
