### ISSUE TITLE
Scran normalisation for Single cell allelic data

### ISSUE THREAD

**Issue by DeepshikhaChandel** [MarioniLab/scran#71]
Such a great tool for Single-cell RNA seq data normalisation! 

Hello Sir,
               So we are currently analysing some Single-cell RNA seq data and we have the allelic read counts for the same. And now we have to normalise those allelic reads. Going through SCran paper and the literature associated with it, makes it seem a very good method for normalising Single cell RNA seq data.

We have some doubts as to how to apply this to allelic read counts. Can you briefly help us with this concern? 

Thanking you in advance,
Deepshikha

**Comment by LTLA** [comment]
Does #62 help?

**Comment by DeepshikhaChandel** [comment]
@LTLA 
Hi,
    Yeah I took a look at #62 , so will doing allelic count normalisation that way take care of all the non-biological variation at allelic level, one of the most crucial one being the sequencing depth/library size ?   


Best,
Deepshikha

**Comment by LTLA** [comment]
The method I have proposed will remove library size differences on a _per-cell_ level. This assumes that differences in capture efficiency and sequencing depth affect cells, not alleles.

Alternatively, you could just treat each allelic profile as a separate library (effectively making a big matrix with twice as many columns) and just throw the entire thing into `calculateSumFactors()`. This will handle differences in coverage of the maternal/paternal alleles, but may also eliminate, e.g., strong imprinting effects.

I would guess that these two strategies will be pretty similar in most applications. If there is any difference, it comes down to whether you believe that a systematic difference in paternal/maternal coverage _within the same cell_ is due to some as-yet-unanticipated technical bias or a biological effect like imprinting.

**Comment by DeepshikhaChandel** [comment]
@LTLA  

Thanks for you valuable response!


Best,
Deepshikha
