### ISSUE TITLE
Can I cluster cells before normalization with PCA + kmeans?

### ISSUE THREAD

**Issue by mt1022** [MarioniLab/scran#8]
Hi,

I noticed that the manual of `quickCluster` recommends using the `igraph` method for dataset with large amount of cells. PCA + kmeans is a very fast clustering method even for large dataset. I would like to known is it appropriate to cluster cells with PCA + kmeans (Will the performance of scran be considerably affected)?

Thanks in advance.

**Comment by LTLA** [comment]
I suppose this would be fine. Obviously, _k_-means requires that you know how many clusters you want. However, at least for `quickCluster` purposes, it is okay to over-cluster, provided you still have enough cells in each cluster for deconvolution. The only function of clustering here is to avoid pooling together very different cells in `computeSumFactors`, which is still fulfilled if you split a large cluster into two smaller clusters. So you just specify an "excess" of clusters that does the job.

The only advice I would give is to perform the PCA and _k_-means on the **ranked** expression values, rather than the raw expression values. This is because the ranks are the same regardless of how much scaling was performed, thus avoiding circularities between clustering and normalization. In contrast, if you used the raw count matrix, you would probably just end up clustering by library size; and if you used a library-size normalized count matrix, then your clustering could be skewed by composition biases. Try using `get.ranks=TRUE` in `quickCluster` and running your clustering method on that.

**Comment by mt1022** [comment]
Thanks for the explanation and the suggestion, both of which are very helpful!
